version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.120.14.124
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  jupyter:
    build: 
      context: ./jupyterDockerFile
      dockerfile: env
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - /home/ccp/project/kafka-docker/IOT:/home/jovyan/work
    command: "start-notebook.sh --NotebookApp.token=''"
  mysql:
    image: mysql:5.7.25
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /home/ccp/project/kafka-docker/mysql:/tmp/mysql
      - /home/ccp/project/kafka-docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: ccp
      MYSQL_PASSWORD: ccp
  admin:
    image: adminer
    container_name: admin
    restart: always
    ports:
      - "8080:8080"
